---
title: "Which Bus Now?"
author: "Miles McBain"
date: "31 March 2017"
output: html_document
---
```{r}
library(readr)
library(tidyverse)
library(lubridate)
```


# Introduction
# Dependencies
# Reference Data
https://translink.com.au/about-translink/open-data
# Learning Outcomes

#Analysis

##Get the data. 
Assumed Present. Code to add from tslumley.

##Unzip data
```{r}
uzip <- utils::unzip("../static_data/SEQ_GTFS.zip")
```

##Import data we need
```{r}
stops <- read_csv("./stops.txt", guess_max = 10000) #a bit hacky
```

##Find a stop based on a query string
```{r}
#' Find a stop
#' @descrpion Find a stop based on a comma separated qury string of search terms:
#' eg: "Montague Rd, Kurilpa Street" to match "Montague Rd at Kurilpa Street"
#' @param stop_names_list a column of stop names
#' @param query the query string
#' @example stops %>% filter(find_stop(stop_name,"Montague Rd, Kurilpa Street"))

find_stop <- function(stop_names_list, query){
    query_pieces <- unlist(strsplit(query, split = "\\s|,"))
    query_pieces <- query_pieces[lapply(query_pieces, nchar) != 0] #drop the exmply matches
    regex_query <- case_when(query_pieces == "Rd" | query_pieces == "Road" ~ "(Rd|Road)",
                            query_pieces == "St" | query_pieces == "Street" ~ "(St|Street)",
                            query_pieces == "Ln" | query_pieces == "Lane" ~ "(Ln|Lane)",
                            TRUE ~ query_pieces) %>%
    paste0(collapse = ".*")
    grepl(x = stop_names_list, pattern = regex_query)#return the logical vector.
}

```

## Find the next departing service from a stop
```{r}
stop_times <- read_csv("stop_times.txt", guess_max = , 
                       col_types = cols(
                          trip_id = col_character(),
                          arrival_time = col_character(),
                          departure_time = col_character(),
                          stop_id = col_character(),
                          stop_sequence = col_character(),
                          pickup_type = col_character(),
                          drop_off_type = col_character()
                       )
              )
trips <- read_csv("trips.txt")
calendar <- read_csv("calendar.txt")
calendar_dates <- read_csv("calendar_dates.txt")

stop_times <-
    stop_times %>%
    mutate(departure_time = as.duration(hms(departure_time))) #convert them to a duration which we can use in date arithmetic

time_now <- now()
time_now_int <- as.numeric(strftime(now(), format = "%Y%m%d"))
day_now <- tolower(wday(lubridate::now(), label = TRUE, abbr = FALSE))
time_now <- duration(hour(time_now)*60 + minute(time_now), units = "minutes")
#Tidy the calendar
tidy_calendar <- gather(calendar, key = "day", value = "day_ind", monday:sunday)

tidy_calendar_dates <-
    calendar_dates %>%
    mutate(day = tolower(wday(
        parse_date_time(date, orders = "%Y%m%d"), label = TRUE, abbr = FALSE)),
        start_date = date,
        end_data = date) %>%
    rename(day_ind = exception_type) %>%
    select(-date)
    
    
viable_services <-
    tidy_calendar %>%
    filter(day == day_now & day_ind == 1) %>%
    anti_join(
        tidy_calendar_dates %>% filter(start_date == time_now_int, day_ind == 2),
        by = c("service_id", "start_date", "day")
    ) %>% 
        bind_rows(tidy_calendar_dates %>% filter(start_date == time_now_int, day_ind == 1)
    )
viable_trips <- 
    viable_services %>%
    left_join(trips)

viable_departures <-     
    viable_trips %>%
    left_join(stop_times) %>%
    mutate(time_until = departure_time - time_now) %>%
    filter(time_until > as.duration(0))

#Find scheduled daprting services
stops %>%
    filter(find_stop(stop_name, "Jindalee")) %>%
    left_join(stop_times) %>%
    inner_join(viable_departures) %>%
    top_n(n = -20, wt = departure_time) %>% 
    select(stop_name, time_until, route_id, trip_headsign)

```



